import CoreText
import CryptoKit
import Testing
import UIKit
@testable import ThumbFree

/// The emoji picker's list: Apple's layout (`tools/emoji/apple-order.txt`) with Unicode's names, generated by
/// `tools/gen-emoji.py`, and only what this iOS draws.
@MainActor @Suite struct EmojiTests {
    private var all: [Emoji] { EmojiCatalog.categories.flatMap(\.emoji) }

    private func section(_ category: EmojiCategory) throws -> [Emoji] {
        try #require(EmojiCatalog.categories.first { $0.category == category }).emoji
    }

    @Test func theCategoriesAreApplesInApplesOrder() {
        #expect(EmojiCatalog.categories.map(\.category) == [.smileysAndPeople, .animalsAndNature, .foodAndDrink, .activity,
                                                           .travelAndPlaces, .objects, .symbols, .flags])
        #expect(EmojiCategory.allCases.first == .recents) // Frequently Used leads Apple's bar
        for section in EmojiCatalog.categories { #expect(!section.emoji.isEmpty, "\(section.category) is empty") }
        for category in EmojiCategory.allCases {
            #expect(!category.title.isEmpty)
            #expect(UIImage(systemName: category.symbol) != nil, "no SF Symbol named \(category.symbol)")
        }
    }

    // Apple's layout, not Unicode's groups: each category starts where Apple's does, the hearts sit in Symbols and the
    // sports in Activity, the flags run by country name, and each emoji is typed as Apple's keyboard types it (the soccer
    // ball with its emoji selector, which Unicode's list leaves off).
    @Test func theListIsApplesLayout() throws {
        #expect(try section(.smileysAndPeople).first == Emoji(text: "\u{1F600}", name: "grinning face"))
        #expect(try section(.animalsAndNature).first == Emoji(text: "\u{1F436}", name: "dog face"))
        #expect(try section(.foodAndDrink).first == Emoji(text: "\u{1F34F}", name: "green apple"))
        #expect(try section(.activity).first == Emoji(text: "\u{26BD}\u{FE0F}", name: "soccer ball"))
        #expect(try section(.travelAndPlaces).first == Emoji(text: "\u{1F697}", name: "automobile"))
        #expect(try section(.objects).first == Emoji(text: "\u{231A}\u{FE0F}", name: "watch"))
        #expect(try section(.symbols).first == Emoji(text: "\u{1FA77}", name: "pink heart"))
        #expect(try section(.symbols).contains(Emoji(text: "\u{2764}\u{FE0F}", name: "red heart")))
        #expect(try section(.activity).contains(Emoji(text: "\u{1F3C4}", name: "person surfing")))
        let flags = try section(.flags)
        #expect(flags.prefix(3).map(\.name) == ["white flag", "black flag", "pirate flag"])
        let countries = flags.drop { !$0.name.hasPrefix("flag: ") }.map(\.name)
        #expect(countries.prefix(3) == ["flag: United Nations", "flag: Afghanistan", "flag: \u{00C5}land Islands"])
        #expect(flags.contains(Emoji(text: "\u{1F1FA}\u{1F1F8}", name: "flag: United States")))
    }

    // All of Apple's layout, not a sample: every section and the starting Frequently Used, each in order, as
    // tools/emoji/apple-order.txt holds them (one digest of the whole order, so a change anywhere in the middle fails too),
    // and the generated file's header records that file's full SHA-256.
    @Test func theWholeOrderIsApplesAsRead() throws {
        let root = URL(fileURLWithPath: #filePath).deletingLastPathComponent().deletingLastPathComponent()
        let order = try Data(contentsOf: root.appendingPathComponent("tools/emoji/apple-order.txt"))
        let read = try #require(String(data: order, encoding: .utf8)).split(separator: "\n").dropFirst().map(String.init) // a comment first
        let generated = [EmojiCategory.recents.title.uppercased() + "\t" + EmojiData.recentsDefault] + EmojiData.categories.map { category, table in
            category.title.uppercased() + "\t" + EmojiCatalog.parse(table, upTo: .infinity).map(\.text).joined(separator: " ")
        }
        func digest(_ data: Data) -> String { SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined() }
        let changed = zip(generated, read).filter { $0 != $1 }.map { $0.0.prefix { $0 != "\t" } }
        #expect(digest(Data(generated.joined(separator: "\n").utf8)) == digest(Data(read.joined(separator: "\n").utf8)),
                "the generated order is not apple-order.txt's (sections: \(changed), \(generated.count) against \(read.count))")
        let header = try String(contentsOf: root.appendingPathComponent("Shared/EmojiData.swift"), encoding: .utf8).prefix(2_000)
        #expect(header.contains("\n// \(digest(order)) tools/emoji/apple-order.txt\n"), "the header does not record apple-order.txt's SHA-256")
    }

    // Apple's keyboard leaves out some of Unicode's emoji (the families made of men, women, girls and boys, and flags
    // that repeat another country's); so does the picker.
    @Test func whatAppleLeavesOutIsLeftOut() {
        #expect(!all.contains { $0.name == "family: man, woman, boy" })
        #expect(!all.contains { $0.name == "flag: Bouvet Island" })
        #expect(all.contains { $0.name == "family: adult, adult, child" })
    }

    // Every cell types one emoji, so one delete takes it away again, and VoiceOver reads a name, never the glyph.
    @Test func everyEmojiIsOneCharacterWithAName() {
        #expect(all.count > 1_800)
        #expect(Set(all.map(\.text)).count == all.count, "an emoji is listed twice")
        for emoji in all {
            #expect(emoji.text.count == 1, "\(emoji.name) is not one character")
            #expect(!emoji.name.isEmpty && emoji.name != emoji.text)
        }
    }

    // Skin-tone variants are not cells of their own (the tone picker offers them); each is kept with the base shown.
    @Test func theSkinToneVariantsAreKeptApartWithTheirBase() {
        let tones = Set((0x1F3FB...0x1F3FF).compactMap(Unicode.Scalar.init))
        #expect(!all.contains { $0.text.unicodeScalars.contains(where: tones.contains) })
        let lines = EmojiData.skinTones.split(separator: "\n")
        #expect(lines.contains("\u{1F44D} \u{1F44D}\u{1F3FB} 1.0 thumbs up: light skin tone"))
        #expect(lines.contains { $0.hasPrefix("\u{1F48F} ") && $0.hasSuffix("kiss: person, person, light skin tone, medium-light skin tone") })
        let shown = Set(EmojiData.categories.flatMap { EmojiCatalog.parse($0.1, upTo: .infinity) }.map(\.text))
        for line in lines { #expect(line.split(separator: " ").first.map { shown.contains(String($0)) } == true, "no base for \(line)") }
    }

    // Emoji newer than this iOS draws are left out: 17.0 came with iOS 26.4.
    @Test func onlyWhatThisIOSDrawsIsShown() throws {
        let table = try #require(EmojiData.categories.first { $0.0 == .smileysAndPeople }).1
        let distortedFace = Emoji(text: "\u{1FAEA}", name: "distorted face") // Emoji 17.0
        #expect(!EmojiCatalog.parse(table, upTo: 16.0).contains(distortedFace))
        #expect(EmojiCatalog.parse(table, upTo: 17.0).contains(distortedFace))
        if #available(iOS 26.4, *) { #expect(all.contains(distortedFace)) }
    }

    // What makes the version gate safe: on the test Simulator every emoji shown draws exactly one emoji wide in Apple's
    // emoji font. An emoji this iOS lacks falls back to a wider box, and a sequence it lacks falls apart into two or more.
    // (A glyph count would not do: Apple draws a couple as a zero-width layer over one glyph.)
    @Test func everyShownEmojiDrawsAsOneGlyph() {
        let font = CTFontCreateWithName("AppleColorEmoji" as CFString, 32, nil)
        func width(_ text: String) -> Double {
            CTLineGetTypographicBounds(CTLineCreateWithAttributedString(NSAttributedString(string: text, attributes: [.font: font])), nil, nil, nil)
        }
        let one = width("\u{1F600}")
        #expect(width("\u{10FFFD}") != one) // the check itself: a private-use code point no font draws as an emoji
        for emoji in all { #expect(width(emoji.text) == one, "\(emoji.name) does not draw as one emoji on this iOS") }
    }

    // The memory guard: the screen's scale while there is room (or no limit, as on the Simulator), then bitmaps of at
    // most 64 px and then 40 px, so the emoji still to draw fit in what is left; when iOS does not say (0), at most 64 px.
    // The grid's 32 pt emoji get exactly those bitmaps (2x and 1.25x).
    @Test func emojiDrawFromSmallerBitmapsNearTheMemoryLimit() {
        #expect(EmojiMemory.drawScale(screen: 3, available: nil, pointSize: 32) == 3)
        #expect(EmojiMemory.drawScale(screen: 3, available: 30 << 20, pointSize: 32) == 3) // the screen's scale right at the step
        #expect(EmojiMemory.drawScale(screen: 3, available: (30 << 20) - 1, pointSize: 32) == 2) // one byte under it
        #expect(EmojiMemory.drawScale(screen: 3, available: 15 << 20, pointSize: 32) == 2)
        #expect(EmojiMemory.drawScale(screen: 3, available: (15 << 20) - 1, pointSize: 32) == 1.25)
        #expect(EmojiMemory.drawScale(screen: 3, available: 1, pointSize: 32) == 1.25) // the smallest amount still in that step
        #expect(EmojiMemory.drawScale(screen: 3, available: 0, pointSize: 32) == 2) // iOS not saying, not "none left"
        #expect(EmojiMemory.drawScale(screen: 2, available: 15 << 20, pointSize: 32) == 2)
    }

    // The guard counts pixels, not points: the search's 41.5 pt emoji (38.5 in landscape) stay crisp at the screen's scale
    // while there is room, then draw from no larger a bitmap than the grid's, 64 px and then 40 px, never a hair over.
    @Test func largerEmojiDrawFromNoLargerBitmapsNearTheMemoryLimit() {
        for size: CGFloat in [41.5, 38.5] {
            #expect(EmojiMemory.drawScale(screen: 3, available: nil, pointSize: size) == 3)
            #expect(EmojiMemory.drawScale(screen: 3, available: 30 << 20, pointSize: size) == 3)
            for (available, cap) in [((30 << 20) - 1, 64.0), (15 << 20, 64), ((15 << 20) - 1, 40), (1, 40), (0, 64)] {
                let pixels = size * EmojiMemory.drawScale(screen: 3, available: available, pointSize: size)
                #expect(pixels <= cap && pixels > cap - 0.1, "\(size) pt draws \(pixels) px with \(available) bytes left")
            }
        }
    }

    @Test func everyCellHasAStableIdentifier() {
        let grinning = Emoji(text: "\u{1F600}", name: "grinning face")
        let usa = Emoji(text: "\u{1F1FA}\u{1F1F8}", name: "flag: United States")
        #expect(grinning.codePoints == "1F600")
        #expect(usa.codePoints == "1F1FA_1F1F8")
        #expect(EmojiSection(category: .flags, emoji: [usa]).identifier(at: 0) == "keyboard.emoji.1F1FA_1F1F8")
        // Frequently Used reorders with use, so its cells are named by place.
        #expect(EmojiSection(category: .recents, emoji: [usa, grinning]).identifier(at: 1) == "keyboard.emoji.recent.1")
        #expect(EmojiCategory.flags.identifier == "keyboard.emoji.category.flags")
    }
}
