#!/usr/bin/env python3
"""Writes ThumbFreeKit/Sources/TFCore/Models/ModelCatalog.swift from docs/models/model-manifest.json.

Run after the manifest changes: python3 tools/gen-catalog.py
"""
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MANIFEST = os.path.join(ROOT, "docs", "models", "model-manifest.json")
OUT = os.path.join(ROOT, "ThumbFreeKit", "Sources", "TFCore", "Models", "ModelCatalog.swift")

# Manifest key, Swift name, id, shown as, summary, language hint, only the files in this folder (None: all).
# Speech models, the ones the user picks. The first is the default.
SPEECH = [
    ("parakeet-tdt-0.6b-v2-coreml", "v2", "parakeet-tdt-0.6b-v2", "English", "Most accurate for English", '"en"', None),
    ("parakeet-tdt-0.6b-v3-coreml", "v3", "parakeet-tdt-0.6b-v3", "Multilingual", "Supports 25 languages", "nil", None),
]
# Support models: downloaded with the speech models, never picked, not in `all`. Silero VAD is MIT licensed.
SUPPORT = [
    ("silero-vad-coreml", "silero", "silero-vad", "Speech check", "Tells speech from noise", "nil",
     "silero-vad-unified-256ms-v6.2.1.mlmodelc/"),
]


def entry(manifest, key, name, model_id, shown, summary, hint, folder):
    model = manifest[key]
    files = "\n".join(
        f'            ModelFile(path: "{f["path"]}", bytes: {f["bytes"]}, sha256: "{f["sha256"]}"),'
        for f in model["files"]
        if folder is None or f["path"].startswith(folder)
    )
    return (
        f"    public static let {name} = ModelEntry(\n"
        f'        id: "{model_id}", displayName: "{shown}", summary: "{summary}",\n'
        f'        repo: "FluidInference/{key}", revision: "{model["revision"]}",\n'
        f"        files: [\n{files}\n        ],\n"
        f"        languageHint: {hint})\n"
    )


def main():
    with open(MANIFEST) as f:
        manifest = json.load(f)
    speech = "\n".join(entry(manifest, *m) for m in SPEECH)
    support = "\n".join(
        "    /// Downloaded with the speech models and never picked by the user, so not in `all`.\n" + entry(manifest, *m)
        for m in SUPPORT
    )
    names = ", ".join(m[1] for m in SPEECH)
    text = (
        "// Generated by tools/gen-catalog.py from docs/models/model-manifest.json. Do not edit by hand.\n\n"
        "/// The models ThumbFree downloads, pinned to a revision. Every file is checked by size and SHA-256.\n"
        "public enum ModelCatalog {\n"
        f"{speech}\n"
        f"{support}\n"
        "    /// The speech models the user picks from.\n"
        f"    public static let all: [ModelEntry] = [{names}]\n"
        f"    public static let defaultID = {SPEECH[0][1]}.id\n"
        "}\n"
    )
    with open(OUT, "w") as f:
        f.write(text)
    print(f"wrote {os.path.relpath(OUT, ROOT)}")


if __name__ == "__main__":
    main()
