#!/usr/bin/env python3
"""Keeps android/app/minified-test-rules.pro in step with the device tests.

    cd android && ./gradlew :app:assembleMinifiedTest :app:assembleMinifiedTestAndroidTest \
        -Pthumbfree.testBuildType=minifiedTest && cd .. && python3 android/tools/minified-test-rules.py

The device tests call the app and its libraries directly, and R8 removes, merges, inlines, renames, re-signs or makes
final much of what only the tests use. This reads both minifiedTest APKs and R8's mapping and finds what the test APK
needs that the app APK no longer has: a class, method or field it calls, an abstract method its fakes must implement,
a method it overrides, or a class or method it extends that R8 made final. It adds a keep rule for each, by its
original name, to the rules file's generated section. Keeping one member changes what R8 does with others, so build
again and rerun until it adds nothing.

Exit status: 0 when nothing is missing, 1 when it added rules, 2 when something is missing that no rule here fixes.
Standard library only; the Android SDK comes from ANDROID_HOME or ~/Library/Android/sdk.
"""
import collections
import glob
import os
import re
import struct
import sys
import zipfile

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT = os.path.join(ROOT, "android/app/build/outputs")
APP_APK = os.path.join(OUT, "apk/minifiedTest/app-minifiedTest.apk")
TEST_APK = os.path.join(OUT, "apk/androidTest/minifiedTest/app-minifiedTest-androidTest.apk")
MAPPING = os.path.join(OUT, "mapping/minifiedTest/mapping.txt")
USAGE = os.path.join(OUT, "mapping/minifiedTest/usage.txt")  # what R8 removed
RULES = os.path.join(ROOT, "android/app/minified-test-rules.pro")
MARKER = "# Generated by android/tools/minified-test-rules.py from here on.\n"
# Framework classes resolve on the phone; android.jar lacks the hidden ones.
FRAMEWORK = ("Ljava/", "Ljavax/", "Landroid/", "Ldalvik/", "Lorg/json/", "Lorg/xml/", "Lorg/w3c/", "Lorg/apache/http/",
             "Lsun/", "Llibcore/", "Lcom/android/internal/")
# Annotation types, which the runtime skips when they are missing.
ANNOTATIONS = ("Lkotlin/Metadata;", "Lkotlin/jvm/JvmInline;", "Lkotlin/jvm/JvmStatic;", "Lkotlin/DeprecationLevel;",
               "Lkotlin/ReplaceWith;", "Lkotlin/annotation/", "Lorg/jspecify/")
PRIVATE, STATIC, FINAL, INTERFACE, ABSTRACT = 0x2, 0x8, 0x10, 0x200, 0x400
Class = collections.namedtuple("Class", "flags super interfaces methods fields")  # members: {(name, type): flags}
# Dalvik instruction sizes in 16-bit units, by opcode: 1 unless listed.
SIZES = [1] * 256
for _lo, _hi, _size in [(0x02, 0x02, 2), (0x03, 0x03, 3), (0x05, 0x05, 2), (0x06, 0x06, 3), (0x08, 0x08, 2),
                        (0x09, 0x09, 3), (0x13, 0x13, 2), (0x14, 0x14, 3), (0x15, 0x16, 2), (0x17, 0x17, 3),
                        (0x18, 0x18, 5), (0x19, 0x1a, 2), (0x1b, 0x1b, 3), (0x1c, 0x1c, 2), (0x1f, 0x20, 2),
                        (0x22, 0x23, 2), (0x24, 0x26, 3), (0x29, 0x29, 2), (0x2a, 0x2c, 3), (0x2d, 0x3d, 2),
                        (0x44, 0x6d, 2), (0x6e, 0x72, 3), (0x74, 0x78, 3), (0x90, 0xaf, 2), (0xd0, 0xe2, 2),
                        (0xfa, 0xfb, 4), (0xfc, 0xfd, 3), (0xfe, 0xff, 2)]:
    SIZES[_lo:_hi + 1] = [_size] * (_hi - _lo + 1)
INVOKES = {0x6e: "virtual", 0x6f: "super", 0x70: "direct", 0x71: "static", 0x72: "interface"}


def uleb(b, off):
    result = shift = 0
    while True:
        byte = b[off]
        off += 1
        result |= (byte & 0x7F) << shift
        if byte < 0x80:
            return result, off
        shift += 7


def read_dex(b, classes, refs):
    """Adds b's classes to classes and its type, method and field references to refs."""
    u = lambda off: struct.unpack_from("<I", b, off)[0]
    n_str, o_str, n_type, o_type, n_proto, o_proto, n_field, o_field, n_meth, o_meth, n_cls, o_cls = struct.unpack_from(
        "<12I", b, 0x38)
    strings = []
    for i in range(n_str):
        _, off = uleb(b, u(o_str + 4 * i))
        strings.append(b[off:b.index(b"\0", off)].decode("utf-8", "replace"))
    types = [strings[u(o_type + 4 * i)] for i in range(n_type)]
    type_list = lambda off: [types[struct.unpack_from("<H", b, off + 4 + 2 * k)[0]] for k in range(u(off))] if off else []
    protos = []
    for i in range(n_proto):
        _, ret, params = struct.unpack_from("<III", b, o_proto + 12 * i)
        protos.append("(" + "".join(type_list(params)) + ")" + types[ret])
    fields = [(types[c], strings[n], types[t]) for c, t, n in
              (struct.unpack_from("<HHI", b, o_field + 8 * i) for i in range(n_field))]
    methods = [(types[c], strings[n], protos[p]) for c, p, n in
               (struct.unpack_from("<HHI", b, o_meth + 8 * i) for i in range(n_meth))]
    calls, accesses = set(), set()  # (method, invoke kind), (field, static access)

    def scan(code):
        n, at = u(code + 12), code + 16
        pc = 0
        while pc < n:
            unit = struct.unpack_from("<H", b, at + 2 * pc)[0]
            op = unit & 0xFF
            if unit == 0x100:  # packed-switch payload
                pc += 4 + 2 * struct.unpack_from("<H", b, at + 2 * pc + 2)[0]
                continue
            if unit == 0x200:  # sparse-switch payload
                pc += 2 + 4 * struct.unpack_from("<H", b, at + 2 * pc + 2)[0]
                continue
            if unit == 0x300:  # fill-array-data payload
                width, size = struct.unpack_from("<HI", b, at + 2 * pc + 2)
                pc += 4 + (width * size + 1) // 2
                continue
            idx = struct.unpack_from("<H", b, at + 2 * pc + 2)[0] if SIZES[op] > 1 else 0
            if 0x6e <= op <= 0x72 or 0x74 <= op <= 0x78:
                calls.add((methods[idx], INVOKES[op if op <= 0x72 else op - 6]))
            elif 0x52 <= op <= 0x6d:
                accesses.add((fields[idx], op >= 0x60))
            pc += SIZES[op]

    refs.append((types, methods, fields, calls, accesses))
    for i in range(n_cls):
        cls, access, sup, itf, _, _, data, _ = struct.unpack_from("<8I", b, o_cls + 32 * i)
        ms, fs = {}, {}
        if data:
            off, sizes = data, []
            for _ in range(4):
                v, off = uleb(b, off)
                sizes.append(v)
            for group, count in enumerate(sizes):  # static fields, instance fields, direct methods, virtual methods
                idx = 0
                for _ in range(count):
                    diff, off = uleb(b, off)
                    flags, off = uleb(b, off)
                    idx += diff
                    if group < 2:
                        fs[fields[idx][1:]] = flags
                    else:
                        code, off = uleb(b, off)
                        ms[methods[idx][1:]] = flags
                        if code:
                            scan(code)
        classes[types[cls]] = Class(access, types[sup] if sup != 0xFFFFFFFF else None, type_list(itf), ms, fs)


def read_apk(path):
    classes, refs = {}, []
    with zipfile.ZipFile(path) as z:
        for name in sorted(z.namelist()):
            if re.fullmatch(r"classes\d*\.dex", name):
                read_dex(z.read(name), classes, refs)
    return classes, refs


def read_jar(path):
    """android.jar's classes, as read_dex gives them."""
    out = {}
    with zipfile.ZipFile(path) as z:
        for n in z.namelist():
            if not n.endswith(".class"):
                continue
            b = z.read(n)
            count, off, i = struct.unpack_from(">H", b, 8)[0], 10, 1
            pool = [None] * count
            while i < count:
                tag = b[off]
                if tag == 1:
                    ln = struct.unpack_from(">H", b, off + 1)[0]
                    pool[i] = b[off + 3:off + 3 + ln].decode("utf-8", "replace")
                    off += 3 + ln
                elif tag in (7, 8, 16, 19, 20):
                    pool[i] = struct.unpack_from(">H", b, off + 1)[0]
                    off += 3
                elif tag == 15:
                    off += 4
                elif tag in (5, 6):
                    off, i = off + 9, i + 1
                else:
                    off += 5
                i += 1
            name = lambda idx: "L" + pool[pool[idx]] + ";" if idx else None
            access, this, sup, n_itf = struct.unpack_from(">HHHH", b, off)
            off += 8
            itfs = [name(struct.unpack_from(">H", b, off + 2 * k)[0]) for k in range(n_itf)]
            off += 2 * n_itf
            groups = []
            for _ in range(2):  # fields, then methods
                group, n_m = {}, struct.unpack_from(">H", b, off)[0]
                off += 2
                for _ in range(n_m):
                    flags, m_name, m_desc, n_attr = struct.unpack_from(">HHHH", b, off)
                    off += 8
                    for _ in range(n_attr):
                        off += 6 + struct.unpack_from(">I", b, off + 2)[0]
                    group[(pool[m_name], pool[m_desc])] = flags
                groups.append(group)
            out[name(this)] = Class(access, name(sup), itfs, groups[1], groups[0])
    return out


def read_mapping(path):
    """{new class descriptor: original name}, {(new class descriptor, new member name): {original member names}} and
    {original class name: {its members that R8 inlined or moved into another class's}}."""
    classes, members, inlined, cur = {}, collections.defaultdict(set), collections.defaultdict(set), None
    for line in open(path, encoding="utf-8"):
        if line.startswith("#"):
            continue
        if not line.startswith(" "):
            if " -> " in line:
                orig, new = line.rstrip().rstrip(":").split(" -> ")
                cur = "L" + new.replace(".", "/") + ";"
                classes[cur] = orig
            continue
        m = re.match(r"\s+(?:\d+:\d+:)?\S+ ([^\s(]+)(?:\(.*?\))?(?::\d+)*(?::\d+)? -> (\S+)$", line.rstrip())
        if m and cur and "." not in m.group(1):
            members[(cur, m.group(2))].add(m.group(1))
        elif m:  # a dotted name is an inlined frame of another class's member, which R8 may have moved here
            owner, _, member = m.group(1).rpartition(".")
            inlined[owner].add(member)
    return classes, members, inlined


def main():
    sdk = os.environ.get("ANDROID_HOME") or os.path.expanduser("~/Library/Android/sdk")
    jars = sorted(glob.glob(os.path.join(sdk, "platforms/android-*/android.jar")),
                  key=lambda p: [int(x) for x in re.findall(r"\d+", p.split("android-")[-1])])
    platform = read_jar(jars[-1])
    app, _ = read_apk(APP_APK)
    own, test_refs = read_apk(TEST_APK)
    renamed, member_names, inlined = read_mapping(MAPPING)
    java_name = lambda desc: renamed.get(desc) or desc[1:-1].replace("/", ".")
    originals_in = collections.defaultdict(set)  # new class descriptor -> original names of its members
    for (cls, _), names in member_names.items():
        originals_in[cls] |= names

    def above(cls, pool):
        """cls and every class above it that pool defines, nearest first."""
        seen, queue = [], [cls]
        while queue:
            c = queue.pop(0)
            if c and c not in seen and c in pool:
                seen.append(c)
                queue += [pool[c].super] + pool[c].interfaces
        return seen

    def resolves(cls, kind, key, seen=()):
        if cls in own or cls in seen or cls.startswith("["):  # an array's clone()
            return True
        info = app.get(cls) or platform.get(cls)
        if info is None:
            return cls.startswith(FRAMEWORK)
        if key in (info.methods if kind == "method" else info.fields):
            return True
        return any(resolves(c, kind, key, seen + (cls,)) for c in [info.super] + info.interfaces if c)

    def declared(cls, kind, key, seen=()):
        """(class, flags) of the app or framework class that declares the member cls resolves to, or None."""
        info = app.get(cls) or platform.get(cls)
        if info is None or cls in seen:
            return None
        if kind == "method" and key in info.methods:
            return cls, info.methods[key]
        if kind == "field" and key in info.fields:
            return cls, info.fields[key]
        for c in [info.super] + info.interfaces:
            if c and (found := declared(c, kind, key, seen + (cls,))):
                return found
        return None

    missing = set()  # (kind, class descriptor, member name, descriptor)
    for types, methods, fields, calls, accesses in test_refs:
        for t in types:
            t = t.lstrip("[")
            if t.startswith("L") and not t.startswith(FRAMEWORK) and not any(t in d for d in (own, app, platform)):
                missing.add(("class", t, "", ""))
        missing |= {("method", c, n, p) for c, n, p in methods if not resolves(c, "method", (n, p))}
        missing |= {("field", c, n, t) for c, n, t in fields if not resolves(c, "field", (n, t))}
        # R8 makes methods and fields static (a Kotlin object's, for one) and merges interfaces into classes, which a
        # call or access of the other kind no longer reaches.
        for (c, n, p), kind in calls:
            found = declared(c, "method", (n, p))
            if found and found[0] in app:
                holder, flags = found
                if (kind == "static") != bool(flags & STATIC) or \
                        kind in ("virtual", "interface") and (kind == "interface") != bool(app[holder].flags & INTERFACE):
                    missing.add(("method", c, n, p))
        for (c, n, t), static in accesses:
            found = declared(c, "field", (n, t))
            if found and found[0] in app and static != bool(found[1] & STATIC):
                missing.add(("field", c, n, t))
    both = {**app, **own}
    for cls, info in own.items():
        chain = above(cls, both)
        app_chain = [c for c in chain if c not in own]
        # A class the app made final cannot be extended.
        if info.super in app and app[info.super].flags & FINAL:
            missing.add(("class", info.super, "", ""))
        # A concrete test class implements every abstract method above it (fakes of app interfaces, and libraries'
        # service implementations such as kotlinx-coroutines-test's main dispatcher).
        if not info.flags & (ABSTRACT | INTERFACE):
            concrete = {m for c in chain for m, f in both[c].methods.items() if not f & ABSTRACT}
            missing |= {("method", c, n, p) for c in app_chain for (n, p), f in app[c].methods.items()
                        if f & ABSTRACT and (n, p) not in concrete}
        # A method that overrides an app method still does: the app's is neither final nor renamed or re-signed.
        for (n, p), f in info.methods.items():
            if f & (PRIVATE | STATIC) or n.startswith("<"):
                continue
            for c in app_chain:
                gone = not any(m[0] == n for m in app[c].methods)
                renamed_away = gone and (n in originals_in[c] or n in inlined[java_name(c)])  # or inlined away
                resigned = n not in member_names.get((c, n), {n}) and (n, p) not in app[c].methods  # new parameters
                if app[c].methods.get((n, p), 0) & FINAL or renamed_away or resigned:
                    missing.add(("override", c, n, p))
    missing = {m for m in missing if not m[1].startswith(ANNOTATIONS)}

    text = open(RULES, encoding="utf-8").read()
    head, _, body = text.partition(MARKER)
    rules = collections.OrderedDict()
    for line in body.splitlines():
        m = re.fullmatch(r"-keep class (\S+)(?: \{ (.*) \})?", line)
        if m:
            rules[m.group(1)] = {spec.strip() for spec in re.findall(r"[^;]+;", m.group(2) or "")}
    in_app = set(renamed.values()) | set(inlined) | {l.rstrip().rstrip(":") for l in open(USAGE, encoding="utf-8")
                                                if l[:1].strip()}
    added, unfixable = 0, []

    def keep_class(name, spec=None):
        nonlocal added
        if name in rules and (spec is None or spec in rules[name]):
            return False
        rules.setdefault(name, set()).update([spec] if spec else [])
        added += 1
        return True

    # A class both APKs define is loaded once, from either, so it keeps all of its members under their names.
    for desc in set(app) & set(own):
        keep_class(java_name(desc), "*;")

    for kind, cls, name, desc in sorted(missing):
        if java_name(cls) not in in_app:
            print(f"not in the app at all, so not R8's doing: {java_name(cls)} {name}")
            continue
        if kind == "class":
            if not keep_class(java_name(cls)):
                unfixable.append(f"class {java_name(cls)}")
            continue
        # A class that both APKs define, renamed in the app, makes the test's descriptor name another class.
        shared = [t for t in re.findall(r"L[^;]+;", desc) if t in own and java_name(t) in in_app]
        if [keep_class(java_name(t), "*;") for t in shared].count(True):
            continue
        # A renamed member names its declaring class in the mapping; a removed or overridden one has its original name.
        owner, originals = cls, member_names.get((cls, name), {name}) if kind == "override" else {name}
        for c in above(cls, app) if kind != "override" and name != "<init>" else []:  # constructors are not inherited
            if (c, name) in member_names:
                owner, originals = c, member_names[(c, name)]
                break
        entry = rules.setdefault(java_name(owner), set())
        for orig in sorted(originals):
            spec = f"*** {orig};" if kind == "field" else "<init>(...);" if orig == "<init>" else f"*** {orig}(...);"
            if spec in entry:
                unfixable.append(f"{kind} {java_name(owner)}.{orig} {desc}")
            else:
                entry.add(spec)
                added += 1
    body = "".join(f"-keep class {c}" + (" { " + " ".join(sorted(ms)) + " }" if ms else "") + "\n"
                   for c, ms in sorted(rules.items()))
    open(RULES, "w", encoding="utf-8").write(head + MARKER + body)
    for line in unfixable:
        print(f"no rule can fix: {line}")
    print(f"{len(missing)} missing, {added} rules added")
    sys.exit(1 if added else 2 if unfixable else 0)


main()
