import CoreGraphics

/// The emoji picker's pure model (an emoji key like Apple's opens ThumbFree's own picker,
/// laid out as Apple's Emoji keyboard, because iOS gives a keyboard no public way to open Apple's). The list itself is
/// `EmojiData`, generated by `tools/gen-emoji.py` from Apple's layout and Unicode's names; this file reads it and
/// leaves out what this iOS cannot draw. No view and no storage, so it is unit-tested through the app target like
/// `Keyplane`.
struct Emoji: Equatable, Hashable {
    let text: String   // what the tap types: one emoji, as Apple's keyboard types it
    let name: String   // its Unicode name ("grinning face"), what VoiceOver reads

    /// The code points in hex joined by "_" ("1F600", "1F1FA_1F1F8"): a plain token for the UI-test identifier.
    var codePoints: String { text.unicodeScalars.map { String($0.value, radix: 16, uppercase: true) }.joined(separator: "_") }
}

/// Apple's emoji categories, in the order of Apple's bar.
enum EmojiCategory: String, CaseIterable {
    case recents, smileysAndPeople, animalsAndNature, foodAndDrink, activity, travelAndPlaces, objects, symbols, flags

    /// Apple's name: the section title (drawn in capitals) and what VoiceOver reads for the category's icon.
    var title: String {
        switch self {
        case .recents: "Frequently Used"
        case .smileysAndPeople: "Smileys & People"
        case .animalsAndNature: "Animals & Nature"
        case .foodAndDrink: "Food & Drink"
        case .activity: "Activity"
        case .travelAndPlaces: "Travel & Places"
        case .objects: "Objects"
        case .symbols: "Symbols"
        case .flags: "Flags"
        }
    }

    /// The bar's icon: an SF Symbol close to Apple's (drawn by the system, no image files).
    var symbol: String {
        switch self {
        case .recents: "clock"
        case .smileysAndPeople: "face.smiling"
        case .animalsAndNature: "teddybear"
        case .foodAndDrink: "takeoutbag.and.cup.and.straw"
        case .activity: "soccerball"
        case .travelAndPlaces: "car"
        case .objects: "lightbulb"
        case .symbols: "number"
        case .flags: "flag"
        }
    }

    var identifier: String { "keyboard.emoji.category.\(rawValue)" }
}

/// One category's emoji, in the picker's order.
struct EmojiSection: Equatable {
    let category: EmojiCategory
    let emoji: [Emoji]

    /// The cell's UI-test identifier: by place in Frequently Used (which reorders with use), else by code points.
    func identifier(at index: Int) -> String {
        category == .recents ? "keyboard.emoji.recent.\(index)" : "keyboard.emoji.\(emoji[index].codePoints)"
    }
}

enum EmojiCatalog {
    /// The newest emoji version this iOS draws. The iOS 26.2 Simulator's emoji font lacks Emoji 17.0 and 26.5's has it;
    /// Apple adds each year's emoji in the spring x.4 update. When iOS draws a newer version, add its line here, then run
    /// EmojiTests on a Simulator with that iOS: they check every emoji shown draws as one glyph.
    static var drawnVersion: Double {
        if #available(iOS 26.4, *) { return 17.0 }
        return 16.0
    }

    /// Apple's eight fixed categories, with only the emoji this iOS draws. Parsed once, when the picker first opens.
    static let categories: [EmojiSection] = EmojiData.categories.map { category, table in
        EmojiSection(category: category, emoji: parse(table, upTo: drawnVersion))
    }

    /// One `EmojiData` table: each line is the emoji, the emoji version that added it and its name. Lines newer than
    /// `version` are left out.
    static func parse(_ table: String, upTo version: Double) -> [Emoji] {
        table.split(separator: "\n").compactMap { line in
            let parts = line.split(separator: " ", maxSplits: 2)
            guard parts.count == 3, let added = Double(parts[1]), added <= version else { return nil }
            return Emoji(text: String(parts[0]), name: String(parts[2]))
        }
    }
}

/// The keyboard's memory guard for emoji. Each emoji drawn for the first time leaves its bitmap in the system's glyph cache
/// for as long as the keyboard runs, and a keyboard cannot raise its memory limit. Drawing every emoji at 32 pt added 88 MB
/// from the 96 px bitmaps a 3x screen uses, 28 MB from the 64 px ones (2x) and 14 MB from the 40 px ones (1.25x), measured
/// on the Simulator. So new emoji draw at the screen's scale, as Apple's do, while the keyboard has room, and from the
/// smaller bitmaps as it nears its limit: whatever is left to draw then still fits. The smaller bitmaps are counted in
/// pixels, so a larger emoji (the search's 41.5 pt) draws from them too, a little softer, and never from larger ones.
enum EmojiMemory {
    /// The scale to draw a new emoji of `pointSize` at, from the screen's and the bytes left before iOS stops the keyboard
    /// (`os_proc_available_memory()`; nil where there is no limit, as on the Simulator): the screen's with room, then
    /// bitmaps of at most 64 px (2x for 32 pt), then at most 40 px (1.25x). That call also answers 0 to a process it does
    /// not count as an app, so 0 means "not known" and draws at most 64 px: every emoji then fits in 28 MB.
    static func drawScale(screen: CGFloat, available: Int?, pointSize: CGFloat) -> CGFloat {
        guard let available, available < 30 << 20 else { return screen }
        let (scale, pixels): (CGFloat, CGFloat) = available >= 15 << 20 || available <= 0 ? (2, 64) : (1.25, 40)
        // Rounded down to a thousandth, so rounding never takes an emoji a hair past its bitmap, into the next larger one.
        return min(screen, scale, (pixels / pointSize * 1_000).rounded(.down) / 1_000)
    }
}
