// Generated by tools/gen-catalog.py from docs/models/model-manifest.json. Do not edit by hand.

/// The models ThumbFree downloads, pinned to a revision. Every file is checked by size and SHA-256.
public enum ModelCatalog {
    public static let v2 = ModelEntry(
        id: "parakeet-tdt-0.6b-v2", displayName: "English", summary: "Most accurate for English",
        repo: "FluidInference/parakeet-tdt-0.6b-v2-coreml", revision: "ee09c569f73759e6d44c9bd16766f477b2b36d39",
        files: [
            ModelFile(path: "Decoder.mlmodelc/analytics/coremldata.bin", bytes: 243, sha256: "46de1a6fe2e49d19a2125bc91acf020df7f2aea84ba821532aade8427a440b05"),
            ModelFile(path: "Decoder.mlmodelc/coremldata.bin", bytes: 554, sha256: "d200ca07694a347f6d02a3886a062ae839831e094e443222f2e48a14945966a8"),
            ModelFile(path: "Decoder.mlmodelc/metadata.json", bytes: 3427, sha256: "90a279b822496316458febc0ce761ab05954fadd9d66aa97bea077a35fc8f2b2"),
            ModelFile(path: "Decoder.mlmodelc/model.mil", bytes: 13106, sha256: "7b95a5a6b672c652000348a67b6d4d92bb8e176b978c6666fe73c28a4d7ec579"),
            ModelFile(path: "Decoder.mlmodelc/weights/weight.bin", bytes: 14429952, sha256: "27d26890221d82322c1092fd99d7b40578e435d5cf4b83c887c42603caf97aba"),
            ModelFile(path: "Encoder.mlmodelc/analytics/coremldata.bin", bytes: 243, sha256: "42e638870d73f26b332918a3496ce36793fbb413a81cbd3d16ba01328637a105"),
            ModelFile(path: "Encoder.mlmodelc/coremldata.bin", bytes: 485, sha256: "4def7aa848599ad0e17a8b9a982edcdbf33cf92e1f4b798de32e2ca0bc74b030"),
            ModelFile(path: "Encoder.mlmodelc/metadata.json", bytes: 2926, sha256: "58222fbc48c13c49d9715567803cd50cb9c23e4360462e0f8ffcea59a2c73c63"),
            ModelFile(path: "Encoder.mlmodelc/model.mil", bytes: 959769, sha256: "ed7b19156ca29fa7dfd6891deb9fda4b0e8893f68597c985d135736546a43808"),
            ModelFile(path: "Encoder.mlmodelc/weights/weight.bin", bytes: 445187200, sha256: "4adc7ad44f9d05e1bffeb2b06d3bb02861a5c7602dff63a6b494aed3bf8a6c3e"),
            ModelFile(path: "JointDecision.mlmodelc/analytics/coremldata.bin", bytes: 243, sha256: "f1183ba213bb94a918c8d2cad19ab045320618f97f6ca662245b3936d7b090f7"),
            ModelFile(path: "JointDecision.mlmodelc/coremldata.bin", bytes: 534, sha256: "e2c6752f1c8cf2d3f6f26ec93195c9bfa759ad59edf9f806696a138154f96f11"),
            ModelFile(path: "JointDecision.mlmodelc/metadata.json", bytes: 2936, sha256: "ba8d309417b9acd4a175fdb15687de6a941db2f5b06666a60e7cf3cc8e2d3c3c"),
            ModelFile(path: "JointDecision.mlmodelc/model.mil", bytes: 9722, sha256: "93bf82042235127cb81ab537dcae47a1c2e7e242ce4ffdaf772981b45eedc4f0"),
            ModelFile(path: "JointDecision.mlmodelc/weights/weight.bin", bytes: 3453388, sha256: "ca22a65903a05e64137677da608077578a8606090a598abf4875fa6199aaa19d"),
            ModelFile(path: "Preprocessor.mlmodelc/analytics/coremldata.bin", bytes: 243, sha256: "03ab3c1327a054c54c07a40325db967ec574f2c91dcc8192bfa44aa561bcf2d8"),
            ModelFile(path: "Preprocessor.mlmodelc/coremldata.bin", bytes: 494, sha256: "d88ea1fc349459c9e100d6a96688c5b29a1f0d865f544be103001724b986b6d6"),
            ModelFile(path: "Preprocessor.mlmodelc/metadata.json", bytes: 2974, sha256: "fb16c581ff5e1b962e7cb2181ed892cd32f9f84c12b6e80ff3e089f28e35bcbb"),
            ModelFile(path: "Preprocessor.mlmodelc/model.mil", bytes: 27166, sha256: "3e06d16fd061294c8a75be68c43a3b1ed1f593d4a9c35249e9cdbccadc59721e"),
            ModelFile(path: "Preprocessor.mlmodelc/weights/weight.bin", bytes: 298880, sha256: "a5f7df6c7f47147ae9486fe18cc7792f9a44d093ec3c6a11e91ef2dc363c48dc"),
            ModelFile(path: "parakeet_vocab.json", bytes: 18762, sha256: "57019fe3c745772ca83a1b048a4bb951cd51329504ea33d4d83316b96e279a97"),
        ],
        languageHint: "en")

    public static let v3 = ModelEntry(
        id: "parakeet-tdt-0.6b-v3", displayName: "Multilingual", summary: "Supports 25 languages",
        repo: "FluidInference/parakeet-tdt-0.6b-v3-coreml", revision: "7dd20fe6b1797d35f5e3307e8b1732d9a178edfe",
        files: [
            ModelFile(path: "Decoder.mlmodelc/analytics/coremldata.bin", bytes: 243, sha256: "4238c4e81ecd0dc94bd7dfbb60f7e2cc824107c1ffe0387b8607b72833dba350"),
            ModelFile(path: "Decoder.mlmodelc/coremldata.bin", bytes: 554, sha256: "18647af085d87bd8f3121c8a9b4d4564c1ede038dab63d295b4e745cf2d7fb99"),
            ModelFile(path: "Decoder.mlmodelc/metadata.json", bytes: 3427, sha256: "a39e93cd8371b8ded92635c7804fcd0590f0d1dd9415c6d19a0484be073077d9"),
            ModelFile(path: "Decoder.mlmodelc/model.mil", bytes: 13110, sha256: "ef2a0a281695398a62fde86ac269c68f73d5b578d7ed3b31f2ba91a2d1ea1f35"),
            ModelFile(path: "Decoder.mlmodelc/weights/weight.bin", bytes: 23604992, sha256: "48adf0f0d47c406c8253d4f7fef967436a39da14f5a65e66d5a4b407be355d41"),
            ModelFile(path: "Encoder.mlmodelc/analytics/coremldata.bin", bytes: 243, sha256: "42e638870d73f26b332918a3496ce36793fbb413a81cbd3d16ba01328637a105"),
            ModelFile(path: "Encoder.mlmodelc/coremldata.bin", bytes: 485, sha256: "d48034a167a82e88fc3df64f60af963ab3983538271175b8319e7d5720a0fb86"),
            ModelFile(path: "Encoder.mlmodelc/metadata.json", bytes: 2921, sha256: "da24da9cca943fb29d7fa8e376d57fca7cb3aa08ca51b956b0b0e56813f087e9"),
            ModelFile(path: "Encoder.mlmodelc/model.mil", bytes: 959769, sha256: "ed7b19156ca29fa7dfd6891deb9fda4b0e8893f68597c985d135736546a43808"),
            ModelFile(path: "Encoder.mlmodelc/weights/weight.bin", bytes: 445187200, sha256: "e2020f323703477a5b21d7c2d282c403e371afb5962e79877e3033e73ba6f421"),
            ModelFile(path: "JointDecision.mlmodelc/analytics/coremldata.bin", bytes: 243, sha256: "bc69ef031ed427e888b1f3889d13eb373655edd5ac9927de20b5dae281b636b7"),
            ModelFile(path: "JointDecision.mlmodelc/coremldata.bin", bytes: 534, sha256: "f56ded0404498e666ffcd84dda0c393924fc3581345ad03e41429ff560cb97b6"),
            ModelFile(path: "JointDecision.mlmodelc/metadata.json", bytes: 2936, sha256: "3044edab5e4ee331d37cef7100074653c944a0e58184ab618aab183a0e0707bc"),
            ModelFile(path: "JointDecision.mlmodelc/model.mil", bytes: 9723, sha256: "2cb084d7e0dc86ad3ddaa53a9631cdd5d97f19839218845b0e65ca065a4d1a5e"),
            ModelFile(path: "JointDecision.mlmodelc/weights/weight.bin", bytes: 12642764, sha256: "4e0e63d840032f7f07ddb1d64446051166281e5491bf22da8a945c41f6eedb3e"),
            ModelFile(path: "Preprocessor.mlmodelc/analytics/coremldata.bin", bytes: 243, sha256: "c9beeb989c8d66f8be11df59bc6df277ec76cee404f6865b46243835ef562f6d"),
            ModelFile(path: "Preprocessor.mlmodelc/coremldata.bin", bytes: 486, sha256: "dbde3f2300842c1fd51ef3ff948a0bcffe65ffd2dca10707f2509f32c1d65b1d"),
            ModelFile(path: "Preprocessor.mlmodelc/metadata.json", bytes: 2841, sha256: "2a98699e22d279dd37fa1d238aeb1c6db1df0d6fad687775324157689d8f3acf"),
            ModelFile(path: "Preprocessor.mlmodelc/model.mil", bytes: 28181, sha256: "4b8518a956450fec57f06c2a21bdffc26973f7f1fa6842fb38fe917f896b6b93"),
            ModelFile(path: "Preprocessor.mlmodelc/weights/weight.bin", bytes: 491072, sha256: "129b76e3aeafa8afa3ea76d995b964b145fe83700d579f6ff42c4c38fa0968ea"),
            ModelFile(path: "parakeet_vocab.json", bytes: 151122, sha256: "7ec60e05f1b24480736ec0eed40900f4626bce1fa9a60fd700ec7e2a59198735"),
        ],
        languageHint: nil)

    /// Downloaded with the speech models and never picked by the user, so not in `all`.
    public static let silero = ModelEntry(
        id: "silero-vad", displayName: "Speech check", summary: "Tells speech from noise",
        repo: "FluidInference/silero-vad-coreml", revision: "b419383c55c110e2c9271fa6ee0ea83d03c70d96",
        files: [
            ModelFile(path: "silero-vad-unified-256ms-v6.2.1.mlmodelc/analytics/coremldata.bin", bytes: 243, sha256: "8067594eb3126ab8318af507f0c00cabfed40d5fedb8a0ee5075dd02e903d909"),
            ModelFile(path: "silero-vad-unified-256ms-v6.2.1.mlmodelc/coremldata.bin", bytes: 625, sha256: "7db35a4fd995222a7fb0129713473b15d1462572ab4a2e5e4d56bcaad9e40f41"),
            ModelFile(path: "silero-vad-unified-256ms-v6.2.1.mlmodelc/metadata.json", bytes: 3335, sha256: "2740be542c611e1ba358e1849b4e265c65cdf0b17192767e1e5de86a31ac94d6"),
            ModelFile(path: "silero-vad-unified-256ms-v6.2.1.mlmodelc/model.mil", bytes: 176918, sha256: "c6a9d1bf22d413265da0a07a1d14151c3ea2fad296b3aa5859275b33ef1c3270"),
            ModelFile(path: "silero-vad-unified-256ms-v6.2.1.mlmodelc/weights/weight.bin", bytes: 882304, sha256: "53ecc8b5081146140ab654c89109cf001f2183abddd7a2411c5081feeffff063"),
        ],
        languageHint: nil)

    /// The speech models the user picks from.
    public static let all: [ModelEntry] = [v2, v3]
    public static let defaultID = v2.id
}
